baseurl: "" # the subpath of your site, e.g. /blog
url: "https://zenithlawyw.github.io" # the base hostname & protocol for your site, e.g. http://example.com
favicon: "/favicon.ico" # the favicon for your site
title: Zenith Law
email: zenith@zenithlaw.com
author: Zenith Law
twitter_username: zenithlawyw
github_username: zenithlawyw
copyright: "Copyright (c) {currentYear} {author}"
description: >- # this means to ignore newlines until "baseurl:"
  Zenith Law is a polyglot software, platform, and data engineer,
  not only capable of bridging the gap between software 
  development, infrastructure management, and data engineering, 
  but also passionate about transforming raw data into actionable 
  business value, by building robust data platforms, pipelines, 
  and utilising AI-driven tools.

google_analytics: G-P49RPF7579
enableDNT: "false"

hero:
  height: "100vh"

zyw:
  date_format: "%-d %B %Y"

collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"

theme: zyw-theme
sitemap: true
lang: "en"

references:
  compact_breakpoint: 900
  mobile_url_label_min: 18
  mobile_url_label_max: 52
  build_url_label_max: 0

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

translate_langs:
  - lang: en
    text: English
  - lang: zh-TW
    text: 繁體中文
  - lang: zh-CN
    text: 简体中文
  - lang: ja
    text: 日本語
  - lang: ko
    text: 한국인
  - lang: de
    text: Deutsch
  - lang: fr
    text: Français
  - lang: it
    text: Italiano
  - lang: es
    text: Español

translate_reserved_words:
  - 2026 Zenith Law
  - AI
  - Agile
  - Apache Spark
  - Azure
  - CI/CD
  - ChatGPT
  - DataOps
  - DevOps
  - GPT
  - Google Translate
  - Kubernetes
  - LLM
  - MLOps
  - Spark
  - Terraform
  - Zenith
  - Zenith Law

nav_pages:
