source "https://rubygems.org"

gem "github-pages", "~> 232", group: :jekyll_plugins
gem "zyw-theme", "~> 0.1.0", path: "../zyw-theme"
gem "wdm", "~> 0.1", :platforms => [:windows]
gem "http_parser.rb", "~> 0.6.0", :platforms => [:jruby]

group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.12"
end

platforms :windows, :jruby do
  gem "tzinfo", ">= 1", "< 3"
  gem "tzinfo-data"
end
